name: CMake-Windows

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

concurrency:
  group: windows-${{ github.ref }}
  cancel-in-progress: true

env:
  BUILD_TYPE: Release


jobs:
  build:
    runs-on: windows-latest

    steps:
      - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - run: echo "The ${{ github.repository }} repository has been cloned to the runner."

      - uses: actions/checkout@v3
        with:
          submodules: 'true'

      - name: Setup devcmd
        uses: ilammy/msvc-dev-cmd@v1

      - name: Install build tools
        run: |
          choco install ninja

      - uses: lukka/get-cmake@latest

      - name: Make vcpkg .git directory writable
        run: |
          # vcpkg will fail to update if the .git directory is not writable
          attrib -r "c:\vcpkg\.git\*.*" /s

      - name: Restore artifacts, or setup vcpkg for building artifacts
        uses: lukka/run-vcpkg@v10
        id: runvcpkg
        with:
          vcpkgDirectory: C:/vcpkg
          doNotUpdateVcpkg: true
          runVcpkgInstall: true

      - name: Configure CMake
        run: echo ${{github.workspace}} `
          && cmake -B ${{github.workspace}}/build `
          -Thost=x64 `
          -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} `
          -DCMAKE_TOOLCHAIN_FILE="${{ env.RUNVCPKG_VCPKG_ROOT }}/scripts/buildsystems/vcpkg.cmake" `
          -DDEVELOPMENT=ON

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --


      - name: Test
        working-directory: ${{github.workspace}}
        run: ${{github.workspace}}/build/test/${{ env.BUILD_TYPE }}/test_kuiper.exe

